# New studio blog posts, 2016 to 2026. Written in the voice of the original blog.
# Each post: date, title, tags, blocks. A block is a string (paragraph, HTML allowed) or
# ("img", archive-project-src, item-index, caption) or ("url", "/site/path.jpg", caption).

POSTS = [
 dict(date="2016-04-02", title="March of Robots 2016 Wrap-Up", tags=["March of Robots", "robot", "Maya", "Keyshot", "ZBrush"], blocks=[
  "Another March in the books! This was my third go at Dacosta Bayley's March of Robots and I managed to get 27 'bots out the door, which is a personal best. A few days got skipped due to client deadlines, but that's how it goes when you're freelancing.",
  ("img", "march_of_robots_2016", 1, "Day 2. The arcade cabinet bot was a favorite around the house."),
  "This year I tried to push the materials a bit more instead of falling back on the same painted metal look. Some of these are straight out of Maya and KeyShot, a couple were roughed out in ZBrush first, and the arcade cabinet was basically an excuse to model a joystick.",
  ("img", "march_of_robots_2016", 4, "Another one from the set."),
  "The whole set is up on the March of Robots 2016 project page. Huge thanks to everyone who left comments on Instagram throughout the month, it really does keep you going when it's 11pm and you still haven't started the day's bot.",
 ]),
 dict(date="2016-11-15", title="Nuthin' But Mech 4", tags=["Nuthin' But Mech", "Design Studio Press", "3D", "Maya"], blocks=[
  "Volume 4 of Nuthin' But Mech is out now from Design Studio Press and I'm honored to be included once again alongside some incredibly talented mech designers.",
  ("img", "3d-misc-1", 12, "Preview of one of my submissions for Volume 4."),
  "For this round I kept the 3D printing theme going from my Volume 3 pieces, but leaned into a more industrial, worn look. Thumbnail sketches first, then Maya for the hard surface work, and KeyShot for the final renders as usual.",
  "You can grab a copy directly from Design Studio Press. Seeing your work printed in an actual book never gets old!",
 ]),
 dict(date="2017-02-21", title="Meet M4Y4, the New Autodesk Maya Mascot", tags=["Autodesk", "Maya", "mascot", "character", "Arnold"], blocks=[
  "I'm finally able to share this one! Autodesk brought me on to design, model and render the new mascot for the Maya Learning Channel, and M4Y4 is now officially out in the wild.",
  ("img", "m4y4", 0, "M4Y4 taking a closer look at the primitives."),
  "One of the key requirements was that the character had to be real-time friendly so it could live right inside the Maya viewport for training videos. That meant keeping the poly count in check and being smart about the textures rather than throwing SubD at everything. It was a fun constraint to design around.",
  ("img", "m4y4", 2, "The group pose, rendered in Arnold."),
  "It's a bit surreal to have a character of mine show up in the software I've been using since the late 90's. More views are up on the M4Y4 project page.",
 ]),
 dict(date="2017-05-26", title="TikiBot", tags=["TikiBot", "ZBrush", "Maya", "Keyshot", "sketchbook"], blocks=[
  "TikiBot started as a doodle in my sketchbook a couple months back and I kept coming back to it, so this week I finally blocked him out in ZBrush.",
  ("img", "tikibot", 1, "The original sketchbook page."),
  "The carved wood look was the whole point of this one. I retopologized the sculpt in Maya, then spent way too long dialing in the wood grain and the chipped paint in KeyShot. Totally worth it.",
  ("img", "tikibot", 0, "Final render."),
  "Process screenshots and a few more angles are on the TikiBot project page. He may or may not end up as a resin piece at some point, stay tuned.",
 ]),
 dict(date="2017-09-12", title="Adobe VR Bot", tags=["Adobe", "VR", "character", "Keyshot", "ZBrush"], blocks=[
  "Here's a 'bot I designed and rendered for the folks at Adobe to help promote their VR storytelling tools. The brief was a robot painting in VR, so naturally he got a headset, a pair of controllers and a neon lit warehouse to work in.",
  ("img", "adobe_vr_bot5", 1, "Sculpting light in the neon warehouse."),
  "The character was modeled in Maya with the finer surface details done in ZBrush. All the neon tube work and the smoky atmosphere was handled in KeyShot, which continues to surprise me with what it can pull off for environment work.",
  ("img", "adobe_vr_bot5", 0, "Bokeh test render."),
  "Having spent a good amount of time in VR myself over the past year, this one hit close to home. More renders on the project page.",
 ]),
 dict(date="2018-04-10", title="Cell Characters for GIBCO", tags=["GIBCO", "Thermo Fisher", "character design", "Maya", "Keyshot"], blocks=[
  "Just wrapped a really enjoyable character design gig for GIBCO, the cell culture brand from Thermo Fisher Scientific. The ask was to turn cells into appealing characters that could carry a bunch of their media without getting too cartoony for a science audience.",
  ("img", "gibco", 0, "Final concept."),
  "We went through a few rounds of concept exploration before landing on the final look. The trick was keeping enough of the actual cell biology in there that the scientists would be happy, while still giving them eyes and a little personality.",
  ("img", "gibco", 1, "Character line-up."),
  "Concepts and the final line-up are on the GIBCO project page.",
 ]),
 dict(date="2018-12-20", title="Happy Holidays from Sketchbot Studios", tags=["sketchbot", "holidays", "Maya", "Keyshot"], blocks=[
  ("img", "3d-misc-1", 23, "Sketchbot getting the lights up."),
  "It's been a busy year here in LA and I'm looking forward to a little downtime with the family. Thanks to all the clients and fellow artists who made 2018 a good one. Here's Sketchbot doing his part with the lights.",
  "See you in 2019!",
 ]),
 dict(date="2019-06-18", title="Jammin' Alpacas", tags=["animation", "short", "character", "Maya", "Arnold"], blocks=[
  "Been heads down on this one for a while and can finally show some stills. Jammin' Alpacas is a stylized animated short featuring a band of alpacas, a space billboard and plenty of attitude.",
  ("img", "jammin_alpacas", 0, "End shot."),
  "I handled the full character pipeline on this one, from design through modeling, rigging, animation and lighting. It's been a great reminder of why I got into character animation in the first place after a stretch of mostly modeling work.",
  ("img", "jammin_alpacas", 1, "Lex reacts."),
  "More stills are up on the project page and I'll share moving pictures when I'm able.",
 ]),
 dict(date="2020-05-19", title="SCOOB! Mean Machine 3D Concept Tests", tags=["SCOOB", "Warner Bros", "concept", "Maya", "Keyshot"], blocks=[
  "With SCOOB! out now I can share some 3D concept tests I did for Dick Dastardly's Mean Machine for Warner Animation Group.",
  ("img", "scoob", 0, "Mean Machine test 5b."),
  "These were quick iterations exploring silhouette, surfacing and attitude before the vehicle got locked down. Working in 3D at the concept stage is something I've been doing more and more of. It lets the art director spin the model around and see it from angles a drawing can't give you, and KeyShot makes turning around a new material variation a matter of minutes.",
  ("img", "scoob", 1, "Test 5d."),
  "Big thanks to the crew for having me on. The rest of the tests are on the project page.",
 ]),
 dict(date="2020-11-05", title="Afternoon At The Museum", tags=["Unreal Engine", "VR", "Eye Pilots", "sketchbot", "real-time"], blocks=[
  "I've been spending a lot of nights and weekends in Unreal Engine this year and this is the first thing to come out of it that I'm happy to share. Afternoon At The Museum is a real-time proof of concept where the Eye Pilots explore a museum full of my robot work.",
  ("img", "sketchbot_museum", 5, "Sketchbot, on display."),
  "Everything was modeled and rigged in Maya, textured in Substance Painter and assembled and lit in Unreal. Coming from a KeyShot workflow, seeing the lighting update in real time as you move things around is still a little bit magic to me.",
  ("img", "sketchbot_museum", 0, "The Eye Pilots wander the lower level."),
  "This is actually the proof of concept for a larger VR pitch I'm putting together, so expect to hear a lot more about the museum in the coming months. Stills are on the project page.",
 ]),
 dict(date="2021-03-09", title="The Museum of Untold Possibilities", tags=["Epic MegaGrant", "Unreal Engine", "VR", "Quest", "Eye Pilots"], blocks=[
  "Here it is, the big one. I've submitted The Museum of Untold Possibilities to the Epic MegaGrants program and I've put the full pitch up on the site for anyone who wants to read it.",
  ("img", "museum-of-untold-possibilities", 0, "Eye Pilot, untethered."),
  "The short version: CoCo VR meets the World of Sketchbot. A non-game VR museum on Quest where you wander galleries of robots at your own pace, timed exhibitions bring you back, and an Art Lab lets you build your own custom 'bot, export it for 3D printing and view it in AR. Basically everything I've loved about custom toy shows and 3D printing, but virtual.",
  "I'm not doing this alone. Erik Anderson is on board as Unreal engineer and Erik Desiderio is handling music and sound. Two Eriks, one museum.",
  ("img", "museum-of-untold-possibilities", 2, "Proof of concept in engine."),
  "Fingers crossed! Either way, the museum is getting built. Read the whole pitch on the project page.",
 ]),
 dict(date="2022-08-24", title="Hex Mesh Studies", tags=["ZBrush", "Keyshot", "hard surface", "study"], blocks=[
  "A little side project that got out of hand. I've been playing with hex based meshes in ZBrush as a way to get sci-fi surface detail without hand placing every panel, and it turned into a whole series.",
  ("img", "3d-misc-1", 32, "Sphere hex, 2022."),
  "The workflow is pretty simple: start with a clean base, use the hex tiling to drive the panel lines, then mask and inflate to get the depth. The fun part is how quickly you can get to something that looks designed.",
  ("img", "3d-misc-1", 36, "Mech hex."),
  ("img", "3d-misc-1", 37, "Three Teeth."),
  "All of these are in the 3D Misc gallery. I'll put together a proper tutorial if there's interest, let me know on Instagram.",
 ]),
 dict(date="2023-10-31", title="Happy Halloween: SkullBot and Candy Corn Bot", tags=["Halloween", "robot", "Maya", "Keyshot"], blocks=[
  "Couldn't let October go by without at least a couple of seasonal 'bots. SkullBot got a V2 pass this year and Candy Corn Bot is brand new.",
  ("img", "3d-misc-1", 34, "SkullBot V2."),
  ("img", "3d-misc-1", 16, "Candy Corn Bot."),
  "Nothing fancy on the process side, just Maya and KeyShot and a free evening. Happy Halloween everyone!",
 ]),
 dict(date="2024-08-14", title="ZBrush for iPad First Impressions", tags=["ZBrush", "iPad", "Sketchfab", "sculpting"], blocks=[
  "ZBrush for iPad dropped and I've been sculpting on the couch all week. Here's the first real test, an alien head that I started as a quick doodle and kept pushing.",
  ("img", "3d-misc-1", 38, "Alien Head V2, sculpted entirely on iPad."),
  "It's not a toy. Most of what I reach for in desktop ZBrush is here, and the Pencil makes the sculpting feel closer to clay than a Wacom ever has for me. Having it on the iPad means I'm sketching in 3D at times I'd normally just be scrolling on my phone.",
  "I uploaded the head to Sketchfab so you can spin it around yourself, there's a link on the USDZ Files page. More tests to come.",
 ]),
 dict(date="2025-01-28", title="Vision Pro Arrives at the Studio", tags=["Apple Vision Pro", "visionOS", "spatial computing", "Eye Pilots"], blocks=[
  "Well, I did it. After a year of watching from the sidelines I picked up an Apple Vision Pro and it's been living on my desk ever since. I have a lot of thoughts.",
  ("img", "3d-misc-1", 5, "The Eye Pilot has been headset ready for a while now."),
  "The thing that gets me is how natural it feels to look at a 3D model at actual size, sitting on my actual desk, with no controllers. I've been in and out of VR since the first Rift dev kits, and this is the first time I've wanted to model in a headset rather than just look at models in one.",
  "So that's what I'm going to try to do. I've started learning Swift and RealityKit, and I have a few ideas for tools I've always wanted as a character modeler. No promises on timing, but this blog is about to get a lot more spatial.",
 ]),
 dict(date="2025-07-22", title="VRNavDemo: Figuring Out Navigation on Vision Pro", tags=["Apple Vision Pro", "visionOS", "GitHub", "RealityKit", "navigation"], blocks=[
  "First bit of code I've put out in public! VRNavDemo is a small sandbox for testing camera navigation models on Vision Pro, and it's up on my GitHub.",
  "The problem I was trying to solve: when you're modeling in a headset you still want to tumble around an object the way you would in Maya, but doing that in a space where you can also just walk around gets weird fast. The demo lets me try tumble, orbit and fly style navigation against each other and see which one makes me queasy.",
  "Spoiler: the Maya style Y-up tumble won, with rotation stored as just two numbers. Every time I tried to get clever with quaternions it drifted. This is groundwork for something bigger that I'll be talking about soon.",
 ]),
 dict(date="2025-10-09", title="TRON Immersive: End of Line", tags=["TRON", "Apple Vision Pro", "visionOS", "Reality Composer Pro", "Substance Painter", "Maya"], blocks=[
  "The original TRON ignited my passion for computer animation when I first saw it at 16 in 1982. With TRON: Ares hitting theaters this week, I decided to create an homage to the original as a proof of concept for my first spatial website environment for Apple Vision Pro.",
  ("img", "tron", 2, "Building The Grid in Maya."),
  "Here's what that means: if you open the TRON page in Safari on Vision Pro and hit the button, the room around you gets replaced with The Grid, complete with looping Recognizer audio. Crank the Digital Crown to full immersion, push the Safari window off to the side, and enjoy your brief respite from the real world.",
  ("url", "/assets/spatial/tank_SS_V2.jpg", "The Tank. This one and the Recognizer display stereoscopically right in the page."),
  "Modeled and animated in Maya, textured in Substance Painter, assembled in Reality Composer Pro. It uses the new model element and requestImmersive that shipped with visionOS 27, so you'll need to be on the current release.",
  "Go check it out on the TRON page. END OF LINE.",
 ]),
 dict(date="2026-01-20", title="Lost in the Backrooms", tags=["Backrooms", "Apple Vision Pro", "visionOS", "USDZ", "Reality Composer Pro"], blocks=[
  "Second immersive environment for the site is live and this one is a little more unsettling. Sketchbot has wandered into the Backrooms.",
  ("img", "backrooms", 0, "Sketchbot, somewhere on level 0."),
  "After the TRON piece I wanted to see how far I could push an environment while keeping the file size sane for the web. This one has fully baked lighting and came in around 20 megs after a good amount of optimization, which loads quick enough on Vision Pro that it feels instant.",
  "Same deal as The Grid: open the page in Safari on Vision Pro, hit Enter, and the yellow wallpaper is all around you. The hum is optional but recommended.",
 ]),
 dict(date="2026-06-16", title="Introducing Quads", tags=["Quads", "Apple Vision Pro", "visionOS", "modeling", "Logitech Muse", "USDZ"], blocks=[
  "OK, here's the big one I've been hinting at for over a year. Quads is a box modeler for Apple Vision Pro, and it's the app I've wanted since the first time I put the headset on.",
  "You model with your hands. Pinch to grab a vertex, edge or face, pull it where you want it, and the mesh updates right there in your room at real size. Catmull-Clark subdivision is live, with creases, so quads stay quads all the way through to a USDZ that looks right in Quick Look. There's sculpting, a voxel remesh, symmetry, and you can model together with a friend over FaceTime with SharePlay, which is honestly the feature I didn't know I needed.",
  "It also has full support for the Logitech Muse stylus, which I highly recommend for precision work, but it's never required. Hands first, always.",
  "The app is in its final stretch before the App Store. There's a community gallery already up at <a href=\"https://quads.vision\">quads.vision</a> where shared models render as real USDZ right in the browser. If you're a modeler, an educator or a studio and want in on the TestFlight, drop me a line.",
  "Thirty years of pushing points around in Maya and it turns out I still had one more modeler in me. More soon!",
 ]),
 dict(date="2026-08-26", title="Radial Menu is Open Source", tags=["GitHub", "Swift", "visionOS", "Quads", "open source"], blocks=[
  "While building Quads I needed a radial menu that didn't feel arbitrary, and I ended up going way down the rabbit hole on it. So I've pulled it out into its own repo and put it on GitHub for anyone to use.",
  "It's one Swift file with no dependencies that runs on visionOS, macOS, iPadOS and iOS. The geometry is parametric: pick an icon size and a gutter and the ring radius solves itself so nothing ever overlaps. There's also a little tuning app with live sliders, measure guides and audio cues, and it exports the numbers as code you can paste into your project.",
  "The big lesson was that a radial menu should never scroll. Delete is at 7 o'clock, it's always at 7 o'clock, and your hand learns it. Twelve items is the ceiling, eight is comfortable.",
  "Grab it at <a href=\"https://github.com/stevetalkowski/radial-menu\">github.com/stevetalkowski/radial-menu</a>. MIT licensed, go nuts.",
 ]),
 dict(date="2026-09-12", title="New Site, Same Robots", tags=["sketchbot", "website", "Apple Vision Pro", "3D"], blocks=[
  "It's been a minute. The last time I overhauled this site was 2015 and a whole lot has happened since, so it was time. The new site is live, it's fast, and for the first time it actually knows what a Vision Pro is.",
  "Every project is back with full galleries, the entire blog going back to 2007 came along for the ride, and there's a whole new section for the spatial work: Quads, the immersive environments, the USDZ pipeline and the radial menu. If you're reading this on Vision Pro, the 3D models on those pages are real and you can pinch them right out of the page.",
  "The Shop is being rebuilt, so if you're after a Sketchbot figure or a custom, just email me for now.",
  "Thanks for sticking around all these years. Dream it. Build it. Grow it. Sell it. Space it.",
 ]),
]
